/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Feb 27 02:26:37 GMT 2020
 */

package com.google.common.util.concurrent;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TimeoutFuture_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.google.common.util.concurrent.TimeoutFuture"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TimeoutFuture_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.util.concurrent.AbstractFuture$AtomicHelper",
      "com.google.common.util.concurrent.ListenableFuture",
      "com.google.common.util.concurrent.TimeoutFuture",
      "com.google.common.util.concurrent.FluentFuture$TrustedFuture",
      "com.google.common.util.concurrent.GwtFluentFutureCatchingSpecialization",
      "com.google.common.util.concurrent.ForwardingFluentFuture",
      "com.google.common.util.concurrent.AbstractFuture$Trusted",
      "com.google.common.util.concurrent.AbstractFuture$SynchronizedHelper",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper$1",
      "com.google.common.util.concurrent.internal.InternalFutureFailureAccess",
      "com.google.common.util.concurrent.AbstractFuture$SafeAtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture$Listener",
      "com.google.common.util.concurrent.AbstractFuture$Waiter",
      "com.google.common.util.concurrent.AbstractFuture",
      "com.google.common.util.concurrent.FluentFuture"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TimeoutFuture_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.common.util.concurrent.internal.InternalFutureFailureAccess",
      "com.google.common.util.concurrent.AbstractFuture$AtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper$1",
      "com.google.common.util.concurrent.AbstractFuture$UnsafeAtomicHelper",
      "com.google.common.util.concurrent.AbstractFuture",
      "com.google.common.util.concurrent.GwtFluentFutureCatchingSpecialization",
      "com.google.common.util.concurrent.FluentFuture",
      "com.google.common.util.concurrent.FluentFuture$TrustedFuture",
      "com.google.common.util.concurrent.TimeoutFuture",
      "com.google.common.util.concurrent.TimeoutFuture$Fire",
      "com.google.common.util.concurrent.DirectExecutor"
    );
  }
}
